on:
  push:
    branches:
    - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./project/tests.sh
      shell: bash
